algorithm = 'JointOptimization'
# dataset param
dataset = 'cifar-10'
input_channel = 3
num_classes = 10
root = '/data/yfli/CIFAR10'
noise_type = 'sym'
percent = 0.2
seed = 1
loss_type = 'ce'
# model param
model1_type = 'resnet18'
model2_type = 'none'
alpha = 1.2
beta = 0.8
begin = 70 # when to begin updating labels
# train param
gpu = '1'
batch_size = 128
lr = 0.08
retrain_lr = 0.1
epochs = 200
retrain_epochs = 120
num_workers = 4
adjust_lr = 1
epoch_decay_start = 80
momentum = 0.9
weight_decay = 1e-4
# result param
save_result = True
