algorithm = 'StandardCE'
dataset = 'animal10N'
adjust_lr = 1
input_channel = 3
num_classes = 14
root = '/data/yfli/Animal10N'
noise_type = 'sym'
percent = 0.8
seed = 1
loss_type = 'gce'
# model param
model1_type = 'VGG-19'
model2_type = 'none'
# train param
gpu = '1'
batch_size = 64
lr = 0.01
epochs = 120
num_workers = 4
epoch_decay_start = 30
alpha = 5.0
# result param
save_result = True